# Test Models

In [37]:
#James Code
import numpy as np

def colour_specific_MAE(y, y_hat, pixel_threshold=0.8, penalty=100):
    #shape = y.shape
    #z_scale = shape[1]  # 18
    #x_scale = shape[2]  # 768
    #y_scale = shape[3]  # 768

    #Without Penalty, not averaged yet
    MAE = np.absolute(y - y_hat)

    #Determine penalised pixel locations
    RED = np.ones(y[0,:,:].shape)
    RED[(y[0,:,:] >= pixel_threshold) & (y[1,:,:] < pixel_threshold) & (y[2,:,:] < pixel_threshold)] = penalty #Het <= na < verander
    BLUE = np.ones(y[:,:,1].shape)
    BLUE[(y[1,:,:] >= pixel_threshold) & (y[0,:,:] < pixel_threshold) & (y[2,:,:] < pixel_threshold)] = penalty
    GREEN = np.ones(y[:,:,2].shape)
    GREEN[(y[2,:,:] >= pixel_threshold) & (y[0,:,:] < pixel_threshold) & (y[1,:,:] < pixel_threshold)] = penalty
    
    #Add Penalty
    MAE[0,:,:] = MAE[0,:,:] * RED
    MAE[1,:,:] = MAE[1,:,:] * BLUE
    MAE[2,:,:] = MAE[2,:,:] * GREEN
    
    return MAE#np.sum(MAE) / (3*3*3) #(z_scale * x_scale * y_scale * 3)

In [39]:
y = np.array([[[0,0,0],[0,0,0],[1,1,1]],[[1,1,1],[0,0,0],[0,0,0]],[[0,0,0],[1,1,1],[0,0,0]]])
y_hat = np.array([[[0.24,0.36,0.12],[0.37,0.86,0.09],[0.87,0.92,0.7]],[[0.82,0.92,0.87],[0.22,0.43,0.24],[0.17,0.29,0.8]],[[0.07,0.11,0.53],[0.88,0.92,0.87],[0.03,0.17,0.47]]])
print(y)
print(y_hat)

[[[0 0 0]
  [0 0 0]
  [1 1 1]]

 [[1 1 1]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [1 1 1]
  [0 0 0]]]
[[[0.24 0.36 0.12]
  [0.37 0.86 0.09]
  [0.87 0.92 0.7 ]]

 [[0.82 0.92 0.87]
  [0.22 0.43 0.24]
  [0.17 0.29 0.8 ]]

 [[0.07 0.11 0.53]
  [0.88 0.92 0.87]
  [0.03 0.17 0.47]]]


In [33]:
print(y[0,:,:])

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1]])

In [38]:
colour_specific_MAE(y, y_hat)

array([[[2.4e-01, 3.6e-01, 1.2e-01],
        [3.7e-01, 8.6e-01, 9.0e-02],
        [1.3e+01, 8.0e+00, 3.0e+01]],

       [[1.8e+01, 8.0e+00, 1.3e+01],
        [2.2e-01, 4.3e-01, 2.4e-01],
        [1.7e-01, 2.9e-01, 8.0e-01]],

       [[7.0e-02, 1.1e-01, 5.3e-01],
        [1.2e+01, 8.0e+00, 1.3e+01],
        [3.0e-02, 1.7e-01, 4.7e-01]]])